export default function() {
    return [
      {
        name: 'React',
        definition: 'In computing, React (sometimes styled React.js or ReactJS) is a JavaScript library for building user interfaces. It is maintained by Facebook, Instagram and a community of individual developers and corporations. React allows developers to create large web-applications that use data and can change over time without reloading the page. It aims primarily to provide speed, simplicity, and scalability. React processes only user interfaces in applications. This corresponds to View in the Model-View-Controller (MVC) pattern, and can be used in combination with other JavaScript libraries or frameworks in MVC, such as AngularJS.' },
      { name: 'Vue.js',
        definition: 'Vue.js (commonly referred to as Vue; pronounced /vjuː/, like view) is an open-source progressive JavaScript framework for building user interfaces. Integration into projects that use other JavaScript libraries is made easy with Vue because it is designed to be incrementally adoptable. Vue can also function as a web application framework capable of powering advanced single-page applications. Vue.js is a popular JavaScript front-end framework that was built to organize and simplify web development. The project focuses on making ideas in web UI development (components, declarative UI, hot-reloading, time-travel debugging, etc.) more approachable. It attempts to be less opinionated and thus easier for developers to pick up. It features an incrementally adoptable architecture. The core library focuses on declarative rendering and component composition, and can be embedded into existing pages. Advanced features required for complex applications such as routing, state management and build tooling are offered via officially maintained supporting libraries and packages.'
      },
      { name: 'Node.js',
        definition: "Node.js is an open-source, cross-platform JavaScript run-time environment for executing JavaScript code server-side. Historically, JavaScript was used primarily for client-side scripting, in which scripts written in JavaScript are embedded in a webpage's HTML, to be run client-side by a JavaScript engine in the user's web browser. Node.js enables JavaScript to be used for server-side scripting, and runs scripts server-side to produce dynamic web page content before the page is sent to the user's web browser. Consequently, Node.js has become one of the foundational elements of the 'JavaScript everywhere' paradigm, allowing web application development to unify around a single programming language, rather than rely on a different language for writing server side scripts."
      },
      { name: 'jQuery',
        definition: "jQuery is a cross-platform JavaScript library designed to simplify the client-side scripting of HTML. It is free, open-source software using the permissive MIT License. Web analysis indicates that it is the most widely deployed JavaScript library by a large margin. jQuery's syntax is designed to make it easier to navigate a document, select DOM elements, create animations, handle events, and develop Ajax applications. jQuery also provides capabilities for developers to create plug-ins on top of the JavaScript library. This enables developers to create abstractions for low-level interaction and animation, advanced effects and high-level, themeable widgets. The modular approach to the jQuery library allows the creation of powerful dynamic web pages and Web applications."
      },
      { name: 'Velocity',
        definition: "Velocity is a cross-platform JavaScript library designed to simplify the client-side scripting of website animation. Velocity is free, open-source software licensed under the MIT License. It is the most popular open source web animation engine. Velocity's syntax is designed to make it easier to create complex animations for HTML and SVG elements. In addition to its workflow benefits, Velocity provides animation performance that is competitive with CSS-based animation. Velocity achieves its performance by maintaining an internal cache of animation states and minimizing 'layout thrashing', the undesirable behavior that web browsers undergo when visually updating at a fast rate. Altogether, its workflow and performance benefits allow Velocity to be used for sophisticated animation programming that can be integrated into both web and mobile applications. Its broad browser and device support make it ideal for large enterprise distributions that must support low-powered devices. Velocity is used to power the user interfaces of many notable websites, including those of Uber, Samsung, WhatsApp, Tumblr, HTC, Mazda, and Microsoft Windows. It is one of the most favorited projects on the code hosting service GitHub. In 2015, Velocity was nominated for Open Source Project of the Year by The Net Awards."
      },
      { name: 'Highcharts',
        definition: 'Highcharts is a product that was created by the Norway-based company, Highsoft. Highcharts was released in 2009, and it is a charting library written in pure JavaScript. The product is developed in Vik, Norway and has been regularly featured in the national media, such as Finansavisen and Dagsrevyen.'
      },
      { name: 'D3.js',
        definition: "D3.js (or just D3 for Data-Driven Documents) is a JavaScript library for producing dynamic, interactive data visualizations in web browsers. It makes use of the widely implemented SVG, HTML5, and CSS standards. It is the successor to the earlier Protovis framework. In contrast to many other libraries, D3.js allows great control over the final visual result. Its development was noted in 2011, as version 2.0.0 was released in August 2011. D3.js is used on hundreds of thousands of websites. Some popular uses include creating interactive graphics for online news websites, information dashboards for viewing data, and producing maps from GIS map making data. In addition, the exportable nature of SVG enables graphics created by D3 to be used in print publications."
      },
      { name: 'Underscore.js',
        definition: "Underscore.js is a JavaScript library which provides utility functions for common programming tasks. It is comparable to features provided by Prototype.js and the Ruby language, but opts for a functional programming design instead of extending object prototypes. For example, Underscore.js's _.each() function delegates to the host environment's native forEach implementation when present, or a compatible version when absent. The documentation refers to Underscore.js as 'the tie to go along with jQuery's tux, and Backbone.js's suspenders.'' Underscore.js was created by Jeremy Ashkenas, who is also known for Backbone.js and CoffeeScript."
      },
      { name: 'Socket.IO',
        definition: 'Socket.IO is a JavaScript library for realtime web applications. It enables realtime, bi-directional communication between web clients and servers. It has two parts: a client-side library that runs in the browser, and a server-side library for Node.js. Both components have a nearly identical API. Like Node.js, it is event-driven. Socket.IO primarily uses the WebSocket protocol with polling as a fallback option, while providing the same interface. Although it can be used as simply a wrapper for WebSocket, it provides many more features, including broadcasting to multiple sockets, storing data associated with each client, and asynchronous I/O. It can be installed with the npm tool.'
      },
      { name: 'PDF.js',
        definition: 'PDF.js or pdf.js is a JavaScript library intended to render PDF files using the HTML5 Canvas for a safer and web standards compliant web browser rendering of PDF files. The project is led by the Mozilla Foundation after Andreas Gal launched it (initially as an experiment) in 2011. PDF.js can work as a part of a website or of a browser. Originally created as a Firefox extension it is now included in Mozilla Firefox since 2012 (version 15) and is enabled by default since 2013 (version 19). SeaMonkey users need to install the development version of the extension. It is also part of ownCloud and there exists a Chrome/Chromium (web browser) extension.'
      },
      { name: 'JsPHP',
        definition: 'JsPHP is a cross-browser JavaScript library designed to make the PHP application programming interface (API) available in JavaScript environments. It was started by Kevin van Zonneveld as php.js and released as an open-source project in 2008. In late 2011 John Elliot forked the php.js project to JsPHP and released a web-based collaborative integrated development environment (IDE) at www.jsphp.com in an effort to rejuvenate and breathe new life into the project, and as an excuse to develop a content management system (CMS) with features for software developers, such as unit testing and benchmarking. JsPHP is free, open source software, dual-licensed under the MIT License or the GNU General Public License, Version 2. JsPHP is designed to provide a familiar and powerful programming interface for JavaScript programmers with a background in, or integrating with, PHP. JsPHP is a useful supplement to other JavaScript libraries and can be used in Ajax applications and dynamic web pages and web applications.'
      },
      { name: 'Three.js',
        definition: 'Three.js is a cross-browser JavaScript library/API used to create and display animated 3D computer graphics in a web browser. Three.js uses WebGL. The source code is hosted in a repository on GitHub.'
      },
      { name: 'Modernizr',
        definition: 'Modernizr is a JavaScript library which is designed to detect HTML5 and CSS3 features in various browsers, which lets JavaScript avoid using unimplemented features or use a workaround such as a shim to emulate them. Modernizr aims to provide this feature detection in a complete and standardized manner'
      }
    ]
}
